import {Lato} from 'next/font/google'
import './style.css'
import 'bootstrap/dist/css/bootstrap.min.css'

const lato = Lato({
  subsets: ['latin-ext'],
  weight: ['400', '700'],
  style: ['normal', 'italic']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
