name: Build & deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy files
    runs-on: ubuntu-latest

    steps:
      - name: Chekout the repo
        uses: actions/checkout@v4

      - name: Copy to remote
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: .
          target: ${{ secrets.PATH }}

  build:
    name: Build the code on the server
    runs-on: ubuntu-latest
    needs: copy

    environment:
      name: timagribanov.com
      url: https://timagribanov.com

    steps:
      - name: Build and restart the app on the server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.PATH }}; npm i; npm run deploy
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}